export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const SET_NEW_PRODUCT = "SET_NEW_PRODUCT";
export const ONCHANGE_PRODUCT = 'ONCHANGE_PRODUCT';
export const SET_NEW_PRODUCT_ITEM = 'SET_NEW_PRODUCT_ITEM';
export const REMOVE_NEW_PRODUCT_ITEM = 'REMOVE_NEW_PRODUCT_ITEM';